services:
  # Define a web service for your FastAPI application
  - type: web
    name: dtu-convocation-checker
    runtime: docker
    # Render will build from your Dockerfile
    dockerfilePath: ./Dockerfile
    # Configuration options
    envVars:
      # Python should run in unbuffered mode so logs appear immediately
      - key: PYTHON_UNBUFFERED
        value: "1"
      # Add any environment variables your main.py needs here
      # For example, if you use Telegram bot tokens or API keys:
      # - key: TELEGRAM_BOT_TOKEN
      #   sync: false  # This means you'll set it manually in Render dashboard
      # - key: TELEGRAM_CHAT_ID
      #   sync: false
    # Free tier settings
    plan: free
    # Health check endpoint - Render will ping this to know your app is running
    healthCheckPath: /health

    # Configuration options
    envVars:
      # Python should run in unbuffered mode so logs appear immediately
      - key: PYTHON_UNBUFFERED
        value: "1"
      # Playwright configuration for headless environment
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
      # Add any environment variables your main.py needs here
      # For example, if you use Telegram bot tokens or API keys:
      # - key: TELEGRAM_BOT_TOKEN
      #   sync: false  # This means you'll set it manually in Render dashboard
      # - key: TELEGRAM_CHAT_ID
      #   sync: false
    # Free tier settings
    plan: free
    # Health check endpoint - Render will ping this to know your app is running
    healthCheckPath: /health