name: DTU Convocation Checker

on:
  # Schedule to run twice daily - at 9 AM and 6 PM IST
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST (3:30 AM UTC)
    - cron: '30 12 * * *' # 6:00 PM IST (12:30 PM UTC)
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  check-convocation:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Get the code from repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # Step 3: Install Playwright and dependencies
      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium
          playwright install-deps chromium
      
      # Step 4: Run the checking script
      - name: Run convocation checker
        env:
          STUDENT_NAME: ${{ secrets.STUDENT_NAME }}
          ROLL_NUMBER: ${{ secrets.ROLL_NUMBER }}
          DATE_OF_BIRTH: ${{ secrets.DATE_OF_BIRTH }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_convocation.py
      
      # Step 5: Upload screenshot as artifact (backup)
      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: convocation-screenshot
          path: screenshot.png
          retention-days: 7
